SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
      ,(SELECT S1.ITEM_NM
          FROM A_ITEM S1
         where s1.brand_cd = M1.BRAND_CD
           AND S1.ITEM_CD = M1.ITEM_CD
      ) AS ITEM_NM
  FROM A_OUT_D M1
 GROUP BY BRAND_CD, ITEM_CD
 ORDER BY BRAND_CD, SUM(ORDER_QTY) DESC;
 

SELECT M1.BRAND_CD, M1.ITEM_CD, S1.ITEM_NM, SUM(M1.ORDER_QTY)
  FROM A_OUT_D M1
 JOIN A_ITEM S1 ON s1.brand_cd = M1.BRAND_CD
                AND S1.ITEM_CD = M1.ITEM_CD
 GROUP BY M1.BRAND_CD, M1.ITEM_CD, S1.ITEM_NM
 ORDER BY M1.BRAND_CD, SUM(M1.ORDER_QTY) DESC;
 
SELECT DISTINCT OUTBOUND_DATE 
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2019-06-15' AND DATE '2019-06-15' + 10;
 
 
SELECT DISTINCT OUTBOUND_DATE
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 1
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 10;


SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + NO AS ORG_DATE
  FROM CS_NO
 WHERE NO <= :DAYS;
 
SELECT LEVEL AS NO
  FROM DUAL
CONNECT BY LEVEL <= 10;

SELECT *
  FROM CS_NO
 WHERE NO <= TO_DATE(:TO_DATE, 'YYYY-MM-DD') - TO_DATE(:FROM_DATE, 'YYYY-MM-DD') + 1;
 
SELECT TO_DATE(:FROM_DATE, 'YYYY-MM-DD') + NO - 1
 FROM CS_NO
WHERE NO <= TO_DATE(:TO_DATE, 'YYYY-MM-DD') - TO_DATE(:FROM_DATE, 'YYYY-MM-DD') + 1;


SELECT *
  FROM (
        SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + NO AS ORG_DATE
          FROM CS_NO
         WHERE NO <= :DAYS
         ) M1
 WHERE EXISTS (
               SELECT 'TLQKF'
                 FROM LO_OUT_M S1
                WHERE S1.OUTBOUND_DATE = M1.ORG_DATE
               );
               
--:BOX_IPSU
SELECT D2.BRAND_CD, D2.ITEM_CD, D2.ORDER_QTY, 
       TRUNC(D2.ORDER_QTY / :BOX_IPSU) AS BOX_SU, 
       MOD(D2.ORDER_QTY, :BOX_IPSU) AS BOX_NATGAE
  FROM (
        SELECT D1.BRAND_CD, D1.ITEM_CD, SUM(D1.ORDER_QTY) AS ORDER_QTY
          FROM A_OUT_D D1
         GROUP BY D1.BRAND_CD, D1.ITEM_CD
         ORDER BY ORDER_QTY DESC
        ) D2
 WHERE ROWNUM <= 3;