SELECT BRAND_CD
      ,COUNT(*) AS INV_CNT
  FROM A_OUT_m
 GROUP BY BRAND_CD;
 
SELECT BRAND_CD
      ,TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
--      ,TO_CHAR(OUTBOUND_DATE, 'D')
      ,COUNT(*) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
         ,TO_CHAR(OUTBOUND_DATE, 'DY')
         ,TO_CHAR(OUTBOUND_DATE, 'D')
 ORDER BY BRAND_CD
         ,TO_CHAR(OUTBOUND_DATE, 'D');
 
SELECT BRAND_CD
      ,SUBSTR('홀짝', MOD(LTRIM((INVOICE_NO),'#'), 2)-1, 1) AS EVENODD
      ,SUM(ORDER_QTY) AS SUM_QTY
      ,COUNT(*) AS INV_CNT
  FROM A_OUT_D
 GROUP BY BRAND_CD
         ,SUBSTR('홀짝', MOD(LTRIM((INVOICE_NO),'#'), 2)-1, 1)
 ORDER BY BRAND_CD
         ,EVENODD DESC;
 
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)),'Empty..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706215';
 
 SELECT SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN SET_QTY END) AS M01
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN SET_QTY END) AS M02
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN SET_QTY END) AS M03
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN SET_QTY END) AS M04
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN SET_QTY END) AS M05
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN SET_QTY END) AS M06
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN SET_QTY END) AS M07
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN SET_QTY END) AS M08
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN SET_QTY END) AS M09
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN SET_QTY END) AS M10
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN SET_QTY END) AS M11
      ,SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('20190101', 'YYYY-MM-DD') AND TO_DATE('20191231','YYYY-MM-DD');
 
SELECT OUTBOUND_DATE
      ,TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
      ,SUBSTR('홀짝',MOD(LTRIM(INVOICE_NO,'#'),2)-1, 1) AS EVENODD
      ,ORDER_NM
      ,CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' 
            WHEN OUT_TYPE_DIV LIKE 'M2%' THEN '저온' 
            END AS TEMP
  FROM A_OUT_M;
  
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY,
       CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            WHEN ORDER_QTY >= 5            THEN '상' 
       END AS GRADE
  FROM A_OUT_D;
  
SELECT BRAND_CD, TEMP, COUNT(*) AS INV_CNT
  FROM (
        SELECT BRAND_CD
              ,CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' 
                    WHEN OUT_TYPE_DIV LIKE 'M2%' THEN '저온' 
               END AS TEMP
              ,INVOICE_NO
          FROM A_OUT_M
       )
 GROUP BY BRAND_CD, TEMP;
 
SELECT BRAND_CD, GRADE, COUNT(*)
  FROM (
        SELECT BRAND_CD, INVOICE_NO,
               CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
                    WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
                    WHEN ORDER_QTY >= 5            THEN '상' 
               END AS GRADE
          FROM A_OUT_D
       )
 GROUP BY BRAND_CD, GRADE;

SELECT CASE WHEN ROWNUM <= 2 THEN ITEM_CD ELSE 'ETC' END AS NEW_ITEM
      ,SUM(SUM_QTY) AS ORDER_QTY
      FROM (
            SELECT SUM(ORDER_QTY) AS SUM_QTY, ITEM_CD
              FROM A_OUT_D
             GROUP BY ITEM_CD
             ORDER BY SUM(ORDER_QTY) DESC
           )
 GROUP BY CASE WHEN ROWNUM <= 2 THEN ITEM_CD ELSE 'ETC' END;
 
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY, GRADE
  FROM (
        SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY,
               CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
                    WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
                    WHEN ORDER_QTY >= 5            THEN '상' 
               END AS GRADE
          FROM A_OUT_D
         WHERE BRAND_CD = '1001'
         ORDER BY CASE ITEM_CD WHEN 'C' THEN 1 ELSE 2 END, ITEM_CD
       );