SELECT ROWNUM AS RNK
       ,ITEM_CD
       ,QTY_IN_BOX
       ,ORDER_QTY
       ,TRUNC(ORDER_QTY / QTY_IN_BOX) AS BOX_CNT
       ,MOD  (ORDER_QTY , QTY_IN_BOX) AS PCS_CNT
       ,CEIL (ORDER_QTY / QTY_IN_BOX) AS BOX_CNT_TOT
  FROM ( -- 상품코드/박스입수별 출고수량의 합계 구하기
         SELECT ITEM_CD, 
                SUM(ORDER_QTY) AS ORDER_QTY,
                QTY_IN_BOX
          FROM LO_OUT_D
         WHERE INVOICE_NO   BETWEEN '346724706262' 
                            AND     '346724706762'
         GROUP BY ITEM_CD,  QTY_IN_BOX
         ORDER BY ORDER_QTY DESC
       )
 WHERE ROWNUM <= 5;

SELECT NULL AS VAL FROM dual WHERE 1=1;
SELECT NULL AS VAL FROM dual WHERE 1=2;

SELECT NVL(MAX(NULL), 'HELLO') AS VAL
  FROM DUAL
 WHERE 1=2;
 
SELECT OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DY') AS DY, INVOICE_NO, ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001';
  
SELECT OUTBOUND_DATE
       ,TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
       ,INVOICE_NO
       ,SUBSTR('홀짝', MOD(LTRIM((INVOICE_NO),'#'), 2)-1, 1) AS EVENODD
       ,ORDER_NM
  FROM A_OUT_M;