SELECT BRAND_CD, COUNT(*) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
 ORDER BY COUNT(*) DESC;

SELECT BRAND_CD, OUTBOUND_DATE, COUNT(*)
  FROM A_OUT_M
 GROUP BY BRAND_CD, OUTBOUND_DATE
 ORDER BY BRAND_CD, COUNT(*) DESC;
 
SELECT BRAND_CD, SUM(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD;
 
SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD, ITEM_CD
 ORDER BY BRAND_CD, SUM(ORDER_QTY) DESC;
 
SELECT BRAND_CD, MAX(ORDER_QTY), MIN(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD;
 
SELECT INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-02'
   AND OUT_TYPE_DIV IN ('M15','M22')
   AND OUT_BOX_DIV LIKE 'F%'
   AND ORDER_PLACE = '52685'
 ORDER BY OUTBOUND_DATE, INVOICE_NO;
 
SELECT OUTBOUND_DATE, 
       COUNT(*) AS TOT_CNT, 
       COUNT(DISTINCT OUT_BOX_DIV) AS OUT_BOX_CNT, 
       MIN(OUT_BOX_DIV) AS OUT_BOX_MIN, 
       MAX(OUT_BOX_DIV) AS OUT_BOX_MAX
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-02'
   AND OUT_TYPE_DIV IN ('M15','M22')
   AND OUT_BOX_DIV LIKE 'F%'
   AND ORDER_PLACE = '52685'
 GROUP BY OUTBOUND_DATE
 ORDER BY OUTBOUND_DATE;
 
 
SELECT *
  FROM A_OUT_D D
 WHERE (BRAND_CD, INVOICE_NO) IN (SELECT BRAND_CD, INVOICE_NO
                                    FROM A_OUT_M M
                                   WHERE D.INVOICE_NO = M.INVOICE_NO
                                     AND D.BRAND_CD = M.BRAND_CD
                                     AND OUTbOUND_DATE = '2023-01-03');
                         
SELECT *
  FROM A_OUT_D D
 WHERE BRAND_CD = '1001' 
   AND (BRAND_CD, INVOICE_NO) IN (SELECT BRAND_CD, INVOICE_NO
                        FROM A_OUT_M M
                       WHERE D.INVOICE_NO = M.INVOICE_NO
                         AND D.BRAND_CD = M.BRAND_CD
                         AND OUT_TYPE_DIV LIKE 'M1%');
                    
                    
SELECT * 
  FROM A_OUT_M M
 WHERE (BRAND_CD, INVOICE_NO) IN (SELECT BRAND_CD, INVOICE_NO
                                    FROM A_OUT_D D
                                   WHERE D.INVOICE_NO = M.INVOICE_NO
                                     AND D.BRAND_CD = M.BRAND_CD
                                   GROUP BY BRAND_CD, INVOICE_NO
                                  HAVING SUM(ORDER_QTY) >= 3);